apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: rainbear-library
spec:
  selector:
    matchLabels:
      app: rainbear-library
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: rainbear-library
    spec:
      containers:
        - name: rainbear-library
          image: shalini31/rainbear-library:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster