name: Build and Push Docker Image

on:
  push:
    branches:
      #git branch you want to trigger the deployment
      - main
  pull_request:
    branches:
      - main

jobs:
  build: #First Job
    #Ensure this points to your self-hosted runner
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          #Change image-name
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rainbear-library:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          #Change image-name
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rainbear-library:latest

      - name: deploy to k8s
        run:
            #Your runner already has kubectl access to the local cluster
          kubectl apply -f k8s/
